apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "goapi.fullname" .}}
  labels: {{- include "goapi.labels" . | nindent 4}}
data:
  GOAPI_HOST: {{.Values.configmap.goapiHost}}
  GIN_MODE: {{.Values.configmap.ginMode}}
