deployment:
  enableSecurityContext: true
  replicaCount: 1
  image:
    repository: dannylongeuay/ndsq-portfolio
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enableTls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ndsquared.net
      paths:
        - path: /
          pathType: Prefix
    - host: www.ndsquared.net
      paths:
        - path: /
          pathType: Prefix

service:
  port: 5000
  type: "ClusterIP"
