deployment:
  image:
    repository: portfolio-app
ingress:
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
configmap:
  apiBaseUrl: "http://api.localhost:8000"
  goapiBaseUrl: "http://goapi.localhost:8000"
