apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "api.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "api.fullname" . }}
  dataFrom:
  {{- if not .Values.enableFakeSecrets }}
  - key: API
  {{- end }}
  - key: AUTH0
{{- if .Values.enableFakeSecrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-fake
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "api.fullname" . }}-fake
    kind: SecretStore
  target:
    name: {{ include "api.fullname" . }}-fake
  dataFrom:
  - key: API
{{- end }}
