apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
      projectID: "33440703"
{{- if .Values.enableFakeSecrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "api.fullname" . }}-fake
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  provider:
    fake:
      data:
      - key: "API"
        valueMap:
          REDIS_URL: "redis://:supersecurepassword@redis-master:6379"
{{- end }}
