apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-worker
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.deployment.enableSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          args:
            - "dramatiq"
            - "app.main:broker"
          {{- if .Values.deployment.enableSecurityContext }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}-worker:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "api.fullname" . }}-{{ .Values.deployment.secretName }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
