name: GOAPI CD
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/goapi-cd.yaml"
      - "apps/goapi/**"
      - "helm/goapi/**"
jobs:
  goapi-deploy:
    name: GOAPI Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dannylongeuay/ndsq-goapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: apps/goapi/
          tags: "latest,prod-${{ github.sha }}"
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ndsquared-prod-sf03
      - uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - run: helm upgrade goapi helm/goapi/ --install --namespace ndsq --create-namespace --set deployment.image.tag=prod-${{ github.sha }}
        name: Install helm chart
