name: Wedding CI
on:
  pull_request:
    paths:
      - "apps/wedding/**"
      - "helm/wedding/**"
jobs:
  helmdiff:
    name: Helm Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ndsquared-prod-sf03
      - uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - run: helm plugin install https://github.com/databus23/helm-diff
        name: Install helm diff plugin
      - name: Run helm diff
        run: |
          COMMAND_OUTPUT=$(helm diff upgrade wedding helm/wedding/ --install --namespace ndsq --no-color)
          echo "COMMAND_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$COMMAND_OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: wedding-diff
          hide_and_recreate: true
          message: |
            ## Helm Diff:
            ```
            ${{ env.COMMAND_OUTPUT }}
            ```
