apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "portfolio.fullname" .}}
  labels: {{- include "portfolio.labels" . | nindent 4}}
data:
  API_BASE_URL: {{.Values.configmap.apiBaseUrl}}
  GOAPI_BASE_URL: {{.Values.configmap.goapiBaseUrl}}
