apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "portfolio.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "portfolio.fullname" . }}
  dataFrom:
  - key: AUTH0
